/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package org.jto.tabletool


import org.apache.tinkerpop.gremlin.process.traversal.P
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.GraphTraversal
import org.apache.tinkerpop.gremlin.process.traversal.dsl.graph.`__`.*
import org.apache.tinkerpop.gremlin.structure.Vertex
import kotlinx.cli.*


fun <A> As(label: String?, vararg labels: String?): GraphTraversal<A, A> = start<A>().`as`(label, *labels)
fun <A> In(vararg labels: String?): GraphTraversal<A, Vertex> = start<A>().`in`(*labels)
fun <A> Is(predicate: P<A>): GraphTraversal<A, A> = start<A>().`is`(predicate)

enum class InputType {
    GraphDefinitionFile,
    Table
}

enum class OutputDisplay {
    NoOutput,
    Both
}

open class OutputHeaderColumn(
    val name: String,
    val alias: String? = name,
    val ignoredCompare: Boolean = false,
    val ignoredOutputDisplay: OutputDisplay = OutputDisplay.NoOutput
)


fun main(args: Array<String>) {

    val parser = ArgParser("MFT definitions compare tool")
    parser.subcommands(CompareCommand(), ExtractOnlyCommand())
    parser.parse(args)

}






